#
# generate_trace.sh
#
# generates sequence of LBAs that can be used by write_trace_wom.

# MAX_LBA is the maximum # of LBA range that will be generated by this script.
# NUM_SEQ_RUNS is the number of sequential LBA runs that will be done. The range of Sequential write is 0 to MAX_LBA.
# RAND_PERCENTAGE: Percentage of LBAs that should be randomly accessed.
# NUM_RAND_RUNS: Total number of random runs.

if [[ $# -ne 4 ]]; then
	echo "generate_trace.sh [MAX_LBA] [NUM_SEQ_RUNS] [RAND_PERCENTAGE] [NUM_RAND_WC]"
	exit
fi

MAX_LBA=$1

SEQ_RANGE=$MAX_LBA

NUM_SEQ_RUNS=$2

# Seq I/O
# write from 0 to $SEQ_RANGE, $NUM_SEQ_RUNS times.

#echo "Seq I/O"

for i in `seq 1 $NUM_SEQ_RUNS`;
do
	for j in `seq 0 $(($SEQ_RANGE - 1))`;
	do
		echo $j
	done
done

#exit

# Random I/O
# write from 0 

#echo "Rand I/O"

RAND_PERCENTAGE=$3

#echo "Rand Percentage $3"
NUM_RAND_WC=$4

if [[ $3 -eq 0 ]]; then
	exit
fi

if [[ $4 -eq 0 ]]; then
	exit
fi

NUM_RAND_RUNS=`echo "$NUM_RAND_WC * 100 / $RAND_PERCENTAGE" | bc`

#echo "NUM rand RUNs = $NUM_RAND_RUNS"
NUM_RAND_IO_BLOCKS=`echo "$RAND_PERCENTAGE * $MAX_LBA / 100" | bc`

#echo "num rand IO Blocks = $NUM_RAND_IO_BLOCKS"

RAND_BLOCKS=`shuf -i 0-$MAX_LBA -n $NUM_RAND_IO_BLOCKS`

for i in `seq 1 $NUM_RAND_RUNS`;
do
	for j in $RAND_BLOCKS;
	do
		echo $j
	done
done
